platform :ios, '10.0'
use_frameworks!

target 'dealdetails_Example' do
  pod 'dealdetails', :path => '../'
  pod 'AirGap', :path => '../../air-gap/'

  target 'dealdetails_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.0.0'
    pod 'Nimble', '~> 5.1.1'
    pod 'FBSnapshotTestCase'
    pod 'Nimble-Snapshots'
  end
end
